on:
  workflow_call:
    inputs:
      profile:
        required: true
        type: string
      runner:
        required: true
        type: string

jobs:
  prepare:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Read docker.properties and extract front version
        id: front_version
        run: |
          FRONT_VERSION=$(grep '^FRONT_VERSION=' docker.properties | cut -d '=' -f 2)
          echo "::set-output name=version::$FRONT_VERSION"
      - name: Retrieve niffler-auth version
        run: |
          echo "::set-output name=version::$(bash ./gradlew :niffler-auth:printVersion -q)"
        id: auth_version
      - name: Retrieve niffler-currency version
        run: |
          echo "::set-output name=version::$(bash ./gradlew :niffler-currency:printVersion -q)"
        id: currency_version
      - name: Retrieve niffler-gateway version
        run: |
          echo "::set-output name=version::$(bash ./gradlew :niffler-gateway:printVersion -q)"
        id: gateway_version
      - name: Retrieve niffler-spend version
        run: |
          echo "::set-output name=version::$(bash ./gradlew :niffler-spend:printVersion -q)"
        id: spend_version
      - name: Retrieve niffler-userdata version
        run: |
          echo "::set-output name=version::$(bash ./gradlew :niffler-userdata:printVersion -q)"
        id: userdata_version
      - name: Push required props to GITHUB_ENV
        run: |
          echo "PROFILE=${{ inputs.profile }}" >> $GITHUB_ENV
          echo "PREFIX=${{ vars.DOCKER_HUB_ACC }}" >> $GITHUB_ENV
          echo "VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}" >> $GITHUB_ENV
          echo "AUTH_VER=${{ steps.auth_version.outputs.version }}" >> $GITHUB_ENV
          echo "CURRENCY_VER=${{ steps.currency_version.outputs.version }}" >> $GITHUB_ENV
          echo "GATEWAY_VER=${{ steps.gateway_version.outputs.version }}" >> $GITHUB_ENV
          echo "SPEND_VER=${{ steps.spend_version.outputs.version }}" >> $GITHUB_ENV
          echo "USERDATA_VER=${{ steps.userdata_version.outputs.version }}" >> $GITHUB_ENV
          echo "FRONT_VER=${{ steps.front_version.outputs.version }}" >> $GITHUB_ENV
          echo "FRONT_IMAGE=niffler-frontend" >> $GITHUB_ENV
      - name: Docker login
        run: |
          docker login --username ${{ vars.DOCKER_HUB_ACC }} --password "${{ secrets.DOCKER_HUB_PASSWORD }}"
      - name: Summary info
        run: |
          echo "### profile be used: ${{ env.PROFILE }}"
          echo "### niffler-auth version will be used: ${{ env.AUTH_VER }}"
          echo "### niffler-currency version will be used: ${{ env.CURRENCY_VER }}"
          echo "### niffler-gateway version will be used: ${{ env.GATEWAY_VER }}"
          echo "### niffler-spend version will be used: ${{ env.SPEND_VER }}"
          echo "### niffler-userdata version will be used: ${{ env.USERDATA_VER }}"
          echo "### niffler-front version will be used: ${{ env.PREFIX }}/${{ env.FRONT_IMAGE }}-${{ env.PROFILE }}:${{ env.FRONT_VER }}"
