name: spend_deploy_prod
on:
  push:
    branches:
      - master
    paths:
      - 'niffler-spend/**'

jobs:
  checkout:
    runs-on: prod-runner
    steps:
      - uses: actions/checkout@v3

  deploy:
    runs-on: prod-runner
    needs: checkout
    steps:
      - name: Retrieve niffler-spend version
        run: |
          echo "::set-output name=version::$(bash ./gradlew :niffler-spend:printVersion -q)"
        id: spend_version
      - name: Push required props to GITHUB_ENV
        run: |
          echo "PROFILE=prod" >> $GITHUB_ENV
          echo "PREFIX=${{ vars.DOCKER_HUB_ACC }}" >> $GITHUB_ENV
          echo "VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}" >> $GITHUB_ENV
          echo "SPEND_VER=${{ steps.spend_version.outputs.version }}" >> $GITHUB_ENV
      - name: deploy
        working-directory: ./
        run: |
          pwd
          docker login --username ${{ vars.DOCKER_HUB_ACC }} --password "${{ secrets.DOCKER_HUB_PASSWORD }}"
          echo "### niffler-spend version will be used: ${{ env.SPEND_VER }}"
          bash ./gradlew :niffler-spend:jib -Pskipjaxb -x :niffler-e-2-e-tests:test
          docker-compose -f docker-compose.ci.yml pull spend.niffler.dc
          docker-compose -f docker-compose.ci.yml stop spend.niffler.dc && docker-compose -f docker-compose.ci.yml up -d --no-deps spend.niffler.dc
          docker system prune  -a -f
          echo "Done!"
