name: frontend_deploy_prod
on:
  push:
    branches:
      - master
    paths:
      - 'niffler-frontend/**'

jobs:
  checkout:
    runs-on: prod-runner
    steps:
      - uses: actions/checkout@v3

  deploy:
    runs-on: prod-runner
    needs: checkout
    steps:
      - name: Read docker.properties and extract front version
        id: front_version
        run: |
          FRONT_VERSION=$(grep '^FRONT_VERSION=' docker.properties | cut -d '=' -f 2)
          echo "::set-output name=version::$FRONT_VERSION"
      - name: Push required props to GITHUB_ENV
        run: |
          echo "PROFILE=prod" >> $GITHUB_ENV
          echo "PREFIX=${{ vars.DOCKER_HUB_ACC }}" >> $GITHUB_ENV
          echo "VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}" >> $GITHUB_ENV
          echo "FRONT_VER=${{ steps.front_version.outputs.version }}" >> $GITHUB_ENV
          echo "FRONT_IMAGE=niffler-frontend" >> $GITHUB_ENV
      - name: build
        working-directory: ./niffler-frontend
        run: |
          pwd
          docker login --username ${{ vars.DOCKER_HUB_ACC }} --password "${{ secrets.DOCKER_HUB_PASSWORD }}"
          echo "### niffler-front version will be used: ${{ env.PREFIX }}/${{ env.FRONT_IMAGE }}-${{ env.PROFILE }}:${{ env.FRONT_VER }}"
          bash ./docker-build.sh prod push
      - name: deploy
        run: |
          docker-compose -f docker-compose.ci.yml pull frontend.niffler.dc
          docker-compose -f docker-compose.ci.yml stop frontend.niffler.dc && docker-compose -f docker-compose.ci.yml up -d --no-deps frontend.niffler.dc
          docker system prune  -a -f
          echo "Done!"
