name: auth_deploy_stage

on:
  workflow_run:
    workflows: [ e2e ]
    types:
      - completed

jobs:
  prepare:
    if: |
      github.event.workflow_run.event == 'workflow_run' && 
      github.event.workflow_run.name == 'e2e' && 
      github.event.workflow_run.conclusion == 'success' && 
      contains(github.event_path, 'niffler-auth/')
    uses: ./.github/workflows/common-action.yml
    with:
      runner: niffler-stage-runner

  deploy:
    if: |
      github.event.workflow_run.event == 'workflow_run' && 
      github.event.workflow_run.name == 'e2e' && 
      github.event.workflow_run.conclusion == 'success' && 
      contains(github.event_path, 'niffler-auth/')
    runs-on: niffler-stage-runner
    needs: prepare
    steps:
      #   https://github.com/LouisBrunner/checks-action/issues/22#issuecomment-885047551
      - name: Recognize sha ref
        id: sharef
        run: |
          if [ "$EVENT" == 'pull_request' ]
          then
            echo "::set-output name=sha::$(echo ${{github.event.pull_request.head.sha}})"
          elif [ "$EVENT" == 'workflow_run' ]
          then
            echo "::set-output name=sha::$(echo ${{github.event.workflow_run.head_sha}})"
          else
            echo "::set-output name=sha::$(echo $GITHUB_SHA)"
          fi
        env:
          EVENT: ${{ github.event_name }}
          REF: ${{ github.ref }}
      - name: Push required props to GITHUB_ENV
        run: |
          echo "PROFILE=staging" >> $GITHUB_ENV
          echo "PREFIX=${{ vars.DOCKER_HUB_ACC }}" >> $GITHUB_ENV
          echo "VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}" >> $GITHUB_ENV
          echo "AUTH_VER=${{ needs.prepare.outputs.auth-ver }}" >> $GITHUB_ENV
          echo "CURRENCY_VER=${{ needs.prepare.outputs.currency-ver }}" >> $GITHUB_ENV
          echo "GATEWAY_VER=${{ needs.prepare.outputs.gateway-ver }}" >> $GITHUB_ENV
          echo "SPEND_VER=${{ needs.prepare.outputs.spend-ver }}" >> $GITHUB_ENV
          echo "USERDATA_VER=${{ needs.prepare.outputs.userdata-ver }}" >> $GITHUB_ENV
          echo "FRONT_VER=${{ needs.prepare.outputs.front-ver }}" >> $GITHUB_ENV
          echo "FRONT_IMAGE=niffler-frontend" >> $GITHUB_ENV
      - name: Docker login
        run: |
          docker login --username ${{ vars.DOCKER_HUB_ACC }} --password "${{ secrets.DOCKER_HUB_PASSWORD }}"
      - name: build
        working-directory: ./
        run: |
          pwd
          echo "### niffler-auth version will be used: ${{ env.AUTH_VER }}"
          bash ./gradlew :niffler-auth:jib -Pskipjaxb -x :niffler-e-2-e-tests:test
          docker-compose -f docker-compose.ci.yml pull auth.niffler.dc
          docker-compose -f docker-compose.ci.yml stop auth.niffler.dc && docker-compose -f docker-compose.ci.yml up -d --no-deps auth.niffler.dc
          docker system prune -a -f
          echo "Done!"
      - name: Commit Action Status
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          sha: ${{ steps.sharef.outputs.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
