name: currency_deploy_stage
on:
  push:
    branches-ignore:
      - master
    paths:
      - 'niffler-currency/**'

jobs:
  deploy:
    runs-on: stage-runner
    steps:
      - name: Checkout project & set envs
        uses: ./.github/workflows/common-action.yml
        with:
          runner: stage-runner
          profile: staging
      - name: build
        working-directory: ./
        run: |
          pwd
          echo "### niffler-currency version will be used: ${{ env.CURRENCY_VER }}"
          bash ./gradlew :niffler-currency:jib -Pskipjaxb -x :niffler-e-2-e-tests:test
          docker-compose -f docker-compose.ci.yml pull currency.niffler.dc
          docker-compose -f docker-compose.ci.yml stop currency.niffler.dc && docker-compose -f docker-compose.ci.yml up -d --no-deps currency.niffler.dc
          docker system prune  -a -f
          echo "Done!"
