name: userdata_deploy_stage
on:
  push:
    branches-ignore:
      - master
    paths:
      - '.github/workflows/niffler-userdata-staging.yaml'
      - 'niffler-userdata/**'

jobs:
  prepare:
    uses: ./.github/workflows/common-action.yml
    with:
      runner: niffler-stage-runner
      profile: staging
        
  deploy:
    runs-on: niffler-stage-runner
    needs:
      - prepare
    steps:
      - name: build
        working-directory: ./
        run: |
          pwd
          bash ./gradlew :niffler-userdata:jib -Pskipjaxb -x :niffler-e-2-e-tests:test
          docker-compose -f docker-compose.ci.yml pull userdata.niffler.dc
          docker-compose -f docker-compose.ci.yml stop userdata.niffler.dc && docker-compose -f docker-compose.ci.yml up -d --no-deps userdata.niffler.dc
          docker system prune  -a -f
          echo "Done!"
