name: frontend_deploy_stage
on:
  push:
    branches-ignore:
      - master
    paths:
      - 'niffler-frontend/**'

jobs:
  deploy:
    runs-on: stage-runner
    steps:
      - name: Checkout project & set envs
        uses: .github/workflows/reusable/prepare-action-staging.yml
      - name: build
        working-directory: ./niffler-frontend
        run: |
          pwd
          echo "### niffler-front version will be used: ${{ env.PREFIX }}/${{ env.FRONT_IMAGE }}-${{ env.PROFILE }}:${{ env.FRONT_VER }}"
          bash ./docker-build.sh staging push
      - name: deploy
        run: |
          docker-compose -f docker-compose.ci.yml pull frontend.niffler.dc
          docker-compose -f docker-compose.ci.yml stop frontend.niffler.dc && docker-compose -f docker-compose.ci.yml up -d --no-deps frontend.niffler.dc
          docker system prune  -a -f
          echo "Done!"
